project:
  type: website
  output-dir: docs

website:
  title: "Angela's R Projects"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://angechoe.github.io/R-Projects-STA9750/"
  navbar:
    background: primary
    search: false
    right:
      - text: "Home"
        href: index.qmd
      #- text: "Project 1"
        #href: mp01.qmd
      #- text: "Project 2"
        #href: mp02.qmd
      #- text: "Project 3"
        #href: mp03.qmd
      #- text: "Project 4"
        #href: mp04.qmd
    
format:
  html:
    theme: zephyr
    toc: false

editor:
  mode: source