project:
  type: website
  output-dir: docs

website:
  title: "Angela's Data Portfolio"
  description:
    Home for all of Angela's Data Analytics projects
  site-url: "https://angechoe.github.io/Data-Analysis-Projects/"
  navbar:
    background: success
    search: false
    right:
      - text: "Home"
        href: index.qmd
      #- text: "Project 1"
        #href: mp01.qmd
      #- text: "Project 2"
        #href: mp02.qmd
      #- text: "Project 3"
        #href: mp03.qmd
      #- text: "Project 4"
        #href: mp04.qmd
    
format:
  html:
    theme: litera
    toc: false

editor:
  mode: source