project:
  type: website
  output-dir: docs

website:
  title: "Angela's Data Portfolio"
  description: "Home for all of Angela's Data Analytics projects"
  site-url: "https://angechoe.github.io/Data-Analysis-Projects/"
  navbar:
    background: success
    search: false
    right:
      - text: "Home"
        href: index.qmd
      - text: "R Projects"
        menu:
          - text: "Netflix Analysis"
            href: r-projects/mp01.qmd
      - text: "Python Projects"
        menu:
          - text: "Spotify Wrapped Decade Analysis "
            href: python-projects/py01.qmd

format:
  html:
    theme: litera
    toc: false

editor:
  mode: source